# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          partitioned() {
            grep 'using delta' myfile.sql | grep -oP "(?<=PARTITIONED).*?(?=COMMENT)"
          }

          struct() {
            grep -i -w 'STRUCT' myfile.sql
          }

          if partitioned; then
            echo "partitioned"
          else
            echo "not partitioned"
          fi

          if struct; then
            echo "struct"
          else
            echo "not struct"
          fi