name: Reuseable Workflow
on: 
  workflow_dispatch:
    inputs:
      text:
        description: "please enter  text to print"
        type: string
        required: true
      tgt_env:
        description: "choose the tagert environment"
        type: choice
        options:
        - dev_01
        - dev_02
        - dev_03
        

jobs:
  Teasting_Reuseable_Workflow:
    uses: devops-hemant/pipelines_server/.github/workflows/hello.yml@main
    with:
      text: ${{ inputs.text }}
      environment: ${{ inputs.tgt_env }}
    secrets: ${{ secrets.PHONE_NUMBER }}
