# This is a basic workflow to help you get started with Actions

name: text grep

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -x
          data_type() {
            grep -oP "(?<=columnname).*?(?=comment)" test.txt
            }
          
          comment() {
            grep -oP '(?<=comment).*' test.txt
          }
          
          comment_text=$(comment)

          datatype=$(data_type)
          echo "expected type is = $datatype"

          echo "after removing spaces"

          echo $datatype | sed 's/ //g'

          datatype_no_space=$(echo $datatype | sed 's/ //g')

          echo "datatype without space = $datatype_no_space"
          echo "datatype without space = $datatype_no_space" >> $GITHUB_STEP_SUMMARY
          
          sed -i "s/columnname.*comment/columnname $datatype_no_space comment $comment_text/g" test.txt

          cat test.txt